# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'
# Optionally set API keys here instead of exporting environment variables.
# Never commit real keys to source control.
# env:
#   OPENAI_API_KEY: sk-...

prompts:
  - 'Explain {{topic}}' 

providers:
#  - openai:gpt-5
#  - openai:gpt-4.1
  - perplexity:sonar
  - openai:o4-mini
#   - id: perplexity:sonar
#     config:
#       temperature: 0.7
#       max_tokens: 4000

  # Or setup models from other providers
  # - anthropic:messages:claude-4-sonnet-20250514
  # - vertex:gemini-2.5-pro

tests:
  - vars:
      topic: 'machine learning'
    assert:
      - type: conversation-relevance
        threshold: 0.8
